### ISSUE TITLE
local Path notation (Windows)

### ISSUE THREAD

**Issue by batjko** [Phenome/generator-lean-mean#6]
I have added the Windows part to the title because I have no idea if this is different on Linux or Mac, but after scaffolding this generator, `gulp serve` won't work because it cannot find the `gulpfile.coffee` file.

![image](https://cloud.githubusercontent.com/assets/7287076/6561409/056741ee-c689-11e4-89a9-22413de18144.png)

Adding the `"./"` part to the local path in `gulpfile.js` solved the issue.
```javascript
'use strict'
require("coffee-script/register");
require("./gulpfile.coffee");
```

**Comment by Nipher** [comment]
Yeah, this change was commited, see 4852e460edf23c4717b0bd0b13ee67889a83e8e0. 
If you want to know more, this was mentioned in the issue #3.
We have to update the package.json version, but we want to do this with more changes, that we are working on.

**Comment by batjko** [comment]
Ah ok. Well, no worries then.
